version: '3.4'

services:
  angular-tour-of-heroes:
    image: angular-tour-of-heroes
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]